# Generated by Django 2.2b1 on 2019-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_rec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=10)),
                ('last_name', models.CharField(default='', max_length=10)),
                ('designation', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=20)),
                ('company', models.CharField(default='', max_length=20)),
                ('office_ad', models.CharField(default='', max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('cpassword', models.CharField(max_length=10)),
            ],
        ),
    ]
