# Generated by Django 2.2b1 on 2019-04-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0003_signup_rec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup_rec',
            new_name='Signuprec',
        ),
    ]
