# Generated by Django 2.2 on 2019-04-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0006_auto_20190417_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
