# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0008_job_jobapplication_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default='Default Name', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='sites',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='skills',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='video_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
