# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0009_auto_20190503_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(default='Default Cover', max_length=5000),
            preserve_default=False,
        ),
    ]
