# Generated by Django 2.2.1 on 2019-05-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_app', '0015_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='about',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='address',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='country',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(default='', max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='postal_code',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='sites',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.CharField(default='', max_length=1204, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.IntegerField(choices=[(1, 'Matriculate'), (2, 'Intermediate'), (3, 'Graduation'), (4, 'Post-Graduation'), (5, 'PHD')]),
        ),
    ]
